//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 03:28:03 PM WEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.hassani.net/soap")
package net.hassani.soap;
